[package]
name = "wallace-minion"
version = "0.10.9"
edition = "2021"

[workspace]
members = [".", "prisma-cli"]
exclude = ["dep-installer-hack"]

[dependencies]
anyhow = "1"
async-openai = "0.10"
async-trait = "0.1"
aws-config = "0.55"
aws-sdk-comprehend = "0.28"
aws-sdk-polly = "0.28"
base64 = "0.21"
chrono = { version = "0.4.25", default-features = false }
cron = "0.12"
lazy_static = "1"
rand = "0.8"
reqwest = "0.11"
riven = "2.19"
serde = "1"
serde_json = "1"
shuttle-runtime = "0.17.0"
shuttle-secrets = "0.17.0"
strum = "0.24"
symphonia = { version = "0.5.3", default-features = false, features = ["mp3"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = [
    "cache",
    "chrono",
    "gateway",
    "rustls_backend",
    "standard_framework",
    "voice",
]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
rev = "f38021fdf5616da0ddcb85dfc88d9c1eb839d6e6"
# branch = "next"
features = ["builtin-queue"]

[dependencies.prisma-client-rust]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.8"
default-features = false
features = ["postgresql"]

[workspace.dependencies.prisma-client-rust-cli]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.8"
default-features = false
features = ["postgresql"]
