[package]
name = "wallace-minion"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "prisma-cli"]
resolver = "2"

[dependencies]
anyhow = "1"
async-openai = "0.10"
async-trait = "0.1"
aws-config = "0.54"
aws-sdk-comprehend = "0.24"
aws-sdk-polly = "0.24"
base64 = "0.21"
chrono = { version = "0.4.23", default-features = false }
cron = "0.12"
dotenvy = "0.15"
lazy_static = "1"
rand = "0.8"
reqwest = "0.11" # https://docs.rs/openssl/latest/openssl/index.html#automatic
riven = { git = "https://github.com/jonaro00/Riven" }
serde = "1"
serde_json = "1"
shuttle-runtime = "0.12.0"
shuttle-secrets = "0.12.0"
strum = "0.24"
symphonia = { version = "0.5.2", features = ["mp3"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1"

[dependencies.prisma-client-rust]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.6"
default-features = false
features = ["postgresql"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = [
    "cache",
    "chrono",
    "gateway",
    "rustls_backend",
    "standard_framework",
    "voice",
]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "next"
features = ["builtin-queue"]
