[package]
name = "wallace-minion"
version = "0.7.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "prisma-cli"]
resolver = "2"

[dependencies]
anyhow = "1"
async-openai = { git = "https://github.com/jonaro00/async-openai" }
async-trait = "0.1"
chrono = { version = "0.4.23", default-features = false }
cron = "0.12"
dotenvy = "0.15"
lazy_static = "1"
prisma-client-rust = { tag = "0.6.5", git = "https://github.com/Brendonovich/prisma-client-rust", default-features = false, features = [
    "postgresql",
] }
rand = "0.8"
reqwest = "0.11" # https://docs.rs/openssl/latest/openssl/index.html#automatic
riven = { git = "https://github.com/jonaro00/Riven" }
serde = "1"
serde_json = "1"
serenity = { version = "0.11", default-features = false, features = [
    "chrono",
    "standard_framework",
    "cache",
    "rustls_backend",
    "gateway",
] }
shuttle-secrets = "0.11.0"
shuttle-service = { version = "0.11.0", features = ["bot-serenity"] }
strum = "0.24"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1"
