[package]
name = "wallace-minion"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "prisma-cli"]
resolver = "2"

[dependencies]
serenity = { version = "0.11", default-features = false, features = [
    "chrono",
    "standard_framework",
    "cache",
    "rustls_backend",
    "gateway",
] }
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
rand = "0.8"
dotenvy = "0.15"
serde = "1"
serde_json = "1"
# reqwest: sudo apt-get install pkg-config # https://docs.rs/openssl/latest/openssl/index.html#automatic
reqwest = "0.11"
riven = { git = "https://github.com/jonaro00/Riven" }
cron = "0.12"
chrono = { version = "0.4.23", default-features = false }
shuttle-secrets = "0.11.0"
shuttle-service = { version = "0.11.0", features = ["bot-serenity"] }
anyhow = "1"
strum = "0.24"
prisma-client-rust = { tag = "0.6.4", git = "https://github.com/Brendonovich/prisma-client-rust", default-features = false, features = [
    "postgresql",
] }
async-trait = "0.1"
