[package]
name = "wallace-minion"
version = "0.11.7"
edition = "2021"

[workspace]
members = [".", "prisma-cli"]
exclude = ["dep-installer-hack"]

[dependencies]
anyhow = "1"
async-openai = "0.14"
async-trait = "0.1"
aws-config = "0.56"
aws-credential-types = "0.56"
aws-sdk-comprehend = "0.31"
aws-sdk-polly = "0.31"
aws-types = "0.56"
base64 = "0.21"
chrono = { version = "0.4.28", default-features = false }
cron = "0.12"
lazy_static = "1"
rand = "0.8"
reqwest = "0.11"
riven = "2.24"
serde = "1"
serde_json = "1"
shuttle-runtime = "0.27.0"
shuttle-secrets = "0.27.0"
strum = { version = "0.25", features = ["derive"] }
symphonia = { version = "0.5.3", default-features = false, features = ["mp3"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = [
    "cache",
    "chrono",
    "gateway",
    "rustls_backend",
    "standard_framework",
    "voice",
]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "next"
features = ["builtin-queue"]

[dependencies.prisma-client-rust]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.9"
default-features = false
features = ["postgresql"]

[workspace.dependencies.prisma-client-rust-cli]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.9"
default-features = false
features = ["postgresql"]
