[package]
name = "wallace-minion"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
rand = "0.8"
dotenv = "0.15"
time = { version = "0.3", features = ["local-offset"] }
