[package]
name = "wallace-minion"
version = "0.1.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
rand = "0.8"
dotenv = "0.15"
time = { version = "0.3" }
chrono = { version = "0.4", default-features = false }
serde = "1.0"
serde_json = "1.0"
reqwest = "0.11" # reqwest: sudo apt-get install pkg-config # https://docs.rs/openssl/latest/openssl/index.html#automatic
riven = { git = "https://github.com/jonaro00/Riven" }
